name: Ejecutar Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'  # Cada 6 horas

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      M3U_SOURCES: ${{ secrets.M3U_SOURCES }}

    steps:
      - name: Hacer checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Ejecutar el script
        run: python extraer_m3u.py

      - name: Comprobar y hacer commit de lista_varios.m3u si hay cambios
        run: |
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
         git add lista_varios.m3u
         git commit -m "Actualizar lista_varios.m3u"
         git pull origin main --rebase
         git push origin main
         else
          echo "No hay cambios para commitear."
         fi
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



